spring:
  application:
    name: helloworldservice
server:
  port: 0
  servlet:
    context-path: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health, info, shutdown
  endpoint:
    shutdown:
      enabled: true